---
# handlers file for db


- name: start and enable service
  service:
    name: mariadb
    state: started
    enabled: True


- name: restart service
  service:
    name: mariadb
    state: restarted
