
[webservers]

web01 ansible_host=172.31.75.232 ansible_user=ubuntu
web02 ansible_host=172.31.73.157 ansible_user=ec2-user



[dbservers]

db01 ansible_host=172.31.79.224 ansible_user=ubuntu
db02 ansible_host=172.31.76.218 ansible_user=ec2-user
